name: update-printer-output
run-name: Update printer output gist
on:
  workflow_dispatch:
  schedule:
    # At minute 50 past every hour.
    - cron: "50 */1 * * *"
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      INDEX_DOC_ROOT: ${{ github.workspace }}/INDEX_GIST
      FACT_DOC_ROOT: ${{ github.workspace }}/FACT_GIST
      FACT_INDEX_GIST_ID: d401c5675c76d26e60dfb4ea0b985137
      FACT_INDEX_GIST_NAME: theres-never-time-fact-printout-state.txt
      PRINT_DATA_GIST_ID: 8d3e2bbe443b3312e257d8a856caa29d
      PRINT_DATA_GIST_NAME: theres-never-time-printer-output.html

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Node setup
        uses: actions/setup-node@v4

      - name: Clone fact-index gist repo
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://gist.github.com/${{ env.FACT_INDEX_GIST_ID }}.git ${{ env.INDEX_DOC_ROOT }}

      - name: Update fact-index gist file
        id: fact-index
        run: |
          cd ${{ env.INDEX_DOC_ROOT }}
          OLD_NUM=$(cut -d ',' -f2 ${{ env.FACT_INDEX_GIST_NAME }})
          NEW_NUM=$(expr $OLD_NUM + 1)
          echo "INDEX=$OLD_NUM" >> $GITHUB_OUTPUT
          echo $NEW_NUM > ${{ env.FACT_INDEX_GIST_NAME }}

      - name: Commit and push changes to fact-index gist
        run: |
          cd ${{ env.INDEX_DOC_ROOT }}
          git config user.email "robot@github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Increment index"
          git push https://jdwillemse:${{ secrets.GIST_TOKEN }}@gist.github.com/${{ env.FACT_INDEX_GIST_ID }}.git

      - name: show content
        run: echo "Hello ${{ steps.fact-index.outputs.INDEX }}"

      - name: Install dependencies
        run: npm install -w @theres-never-time/output

      - name: Create output file
        # pass the index of the next fact to print to the script
        run: npm run create-output:build -- ${{ steps.fact-index.outputs.INDEX }}

      - name: Clone print gist repo
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://gist.github.com/${{ env.PRINT_DATA_GIST_ID }}.git ${{ env.FACT_DOC_ROOT }}

      - name: Override print gist file
        run: cp -f ${{ env.PRINT_DATA_GIST_NAME }} ${{ env.FACT_DOC_ROOT }}/${{ env.PRINT_DATA_GIST_NAME }}

      - name: Commit and push changes to print gist
        run: |
          cd ${{ env.FACT_DOC_ROOT }}
          git config user.email "robot@github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Update ${{ env.PRINT_DATA_GIST_NAME }}"
          git push https://jdwillemse:${{ secrets.GIST_TOKEN }}@gist.github.com/${{ env.PRINT_DATA_GIST_ID }}.git
