name: update-printer-output
run-name: Update printer output gist
on:
  workflow_dispatch:
  schedule:
    # At minute 50 past every hour.
    - cron: "50 */1 * * *"
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DOC_ROOT: ${{ github.workspace }}/GIST
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Create output file
        run: npm run backend
      - name: Clone gist repo
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://gist.github.com/770f8f7ec5eeaee50f0e288e47d4e8fb.git ${{ env.DOC_ROOT }}
      - name: Override gist file
        run: cp -f print-data.txt ${{ env.DOC_ROOT }}/print-data.txt
      - name: Commit and push changes to gist
        run: |
          cd ${{ env.DOC_ROOT }}
          git config user.email "robot@github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Update print-data.txt"
          git push https://jdwillemse:${{ secrets.GIST_TOKEN }}@gist.github.com/770f8f7ec5eeaee50f0e288e47d4e8fb.git
